export const POPULATE_STORE_W_CARS ='POPULATE_STORE_W_CARS';
export const ADD_CAR = 'ADD_CAR';
export const UPDATE_CAR = 'UPDATE_CAR';
export const REMOVE_CAR = 'REMOVE_CAR';

export const ADD_TOKEN = 'ADD_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';

export const ADD_ADMIN = 'ADD_ADMIN';
export const REMOVE_ADMIN = 'REMOVE_ADMIN';


export const ADD_RENTED_CAR = 'ADD_RENTED_CAR';

export const POPULATE_STORE_W_RESERVATIONS = 'POPULATE_STORE_W_RESERVATIONS';
export const ADD_RESERVATION_START_DATE = 'ADD_RESERVATION_START_DATE';
export const ADD_RESERVATION_END_DATE = 'ADD_RESERVATION_END_DATE';
export const ADD_RESERVATION = 'ADD_RESERVATION';
export const DELETE_RESERVATION = 'DELETE_RESERVATION';
export const UPDATE_RESERVATION = 'UPDATE_RESERVATION';


export const FILTER_RESERVATIONS = 'FILTER_RESERVATIONS';
export const RESERVATION_IS_EDITED = 'RESERVATION_IS_EDITED';
export const DELETE_FILTERED_RESERVATIONS = 'DELETE_FILTERED_RESERVATIONS';
export const DELETE_CERTAIN_FILTERED_RESERVATION = 'DELETE_CERTAIN_FILTERED_RESERVATION';
export const UPDATE_FILTERED_RESERVATION = 'UPDATE_FILTERED_RESERVATION';